import { NextRequest } from 'next/server';
import { withAuth, ok, fail } from '@/lib/with-auth';
import { dbStore } from '@/lib/db-service';
import { recordAuditLog } from '@/lib/audit-logger';

export const POST = withAuth(['admin'], async (req: NextRequest, session) => {
  try {
    const snapshot = await dbStore.createSnapshot();

    await recordAuditLog({
      type: 'admin',
      message: `Database backup snapshot generated by admin user ${session.email}`,
      userId: session.uid,
    });

    return ok({
      message: 'Database backup snapshot generated successfully.',
      snapshot,
    });
  } catch (err: any) {
    return fail(err.message || 'Failed to create backup snapshot', 500);
  }
});
